apiVersion: v1
description: OpenStack-Helm Zookeeper
home: https://zookeeper.apache.org/
maintainers:
- name: OpenStack-Helm Authors
name: zookeeper
sources:
- https://github.com/apache/zookeeper
- https://opendev.org/openstack/openstack-helm-infra
version: 0.1.0-mcp-2703
